# Created by JJ De Rooy
# This aims script automates the setup of the Raspberry Pi server. It automagically installs
# python modules, packages, creates necessary folders, etc.

# Download (git clone) all the files from our GitHub
echo
echo "Creating /htsc and cloning github into it..."
echo
sleep 2
git clone https://github.com/UVicRocketry/Hybrid-Test-Stand-Control /home/pi/Documents/htsc

# Make folder (mkdir) for log files generated by running the engine
echo
echo "Creating logs folder"
echo
sleep 2
mkdir /home/pi/Documents/logs

# Install (pip3) python3 module  phidget22 for stepper motor controller boards
echo
echo "Installing phidget22 package with pip"
echo
sleep 2
pip3 install phidget22

# Installing lib-usb package as per https://www.phidgets.com/docs/OS_-_Linux
echo
echo "Installing libusb"
echo
sleep 2
sudo apt-get install libusb-1.0-0-dev

# Create a cron job to automatically run startserver.sh after booting. Haven't figured out why it needs to be run twice
# to actually create the cron job.
echo
echo "Creating cronjob to automatically start the server after booting..."
echo
sleep 2
echo "@reboot /home/pi/Documents/htsc/server/starthtsc.sh" | crontab -
echo "@reboot /home/pi/Documents/htsc/server/starthtsc.sh" | crontab -

# Delete autoserversetup.sh from home directory
echo
echo "Removing autoserversetup.sh from /home"
echo
sleep 2
rm /home/pi/autoserversetup.sh

# Following the excellent guide posted here: https://artisan-roasterscope.blogspot.com/2017/01/connecting-phidgets-on-linux.html
wget https://www.phidgets.com/downloads/phidget22/libraries/linux/libphidget22.tar.gz
tar zxvf libphidget22.tar.gz
cd libphidget22-*
./configure
make
sudo make install
echo /usr/local/lib >> sudo /etc/ld.so.conf && sudo ldconfig
cd /tmp/libphidget22-*
sudo cp plat/linux/udev/99-libphidget22.rules /etc/udev/rules.d

echo
echo
echo "Please reboot the Raspberry Pi before use!"

