# Created by JJ De Rooy
# This aims script automates the setup of the Raspberry Pi server. It automagically installs
# python modules, packages, creates necessary folders, etc.

# Download (git clone) all the files from our GitHub
echo
echo "Creating /htsc and cloning github into it..."
echo
sleep 2
git clone https://github.com/UVicRocketry/Hybrid-Test-Stand-Control /home/pi/Documents/htsc

# Make folder (mkdir) for log files generated by running the engine
echo
echo "Creating logs folder"
echo
sleep 2
mkdir /home/pi/Documents/logs

# Install (pip3) python3 module  phidget22 for stepper motor controller boards
echo
echo "Installing phidget22 package with pip"
echo
sleep 2
pip3 install phidget22

# Create a cron job to automatically run startserver.sh after booting. Haven't figured out why it needs to be run twice
# to actually create the cron job.
echo
echo "Creating cronjob to automatically start the server after booting..."
echo
sleep 2
echo "@reboot /home/pi/Documents/htsc/server/starthtsc.sh" | crontab -
echo "@reboot /home/pi/Documents/htsc/server/starthtsc.sh" | crontab -

# Delete autoserversetup.sh from home directory
echo
echo "Removing autoserversetup.sh from /home"
echo
sleep 2
rm /home/pi/autoserversetup.sh

# Change directory (cd) to lib and unzip pack (tar) the libphidget22 library. Then make and install it according to INSTALL.txt
cd /home/pi/Documents/htsc/server/lib
echo
echo "Unpacking libphidget22 lib..."
echo
sleep 2
tar xvzf /home/pi/Documents/htsc/server/lib/libphidget22-1.6.20200417.tar.gz

echo
echo "Removing tar file..."
echo
sleep 2
rm libphidget22-1.6.20200417.tar.gz

echo
echo "Making unpacked lib. This will take awhile..."
echo
sleep 2
cd libphidget22-1.6.20200417/
./configure
make

echo
echo "Installing lib..."
echo
sleep 2
sudo make install




